name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install mypy pytest pytest-cov pytest-mock ruff black
        pip install -e .

    - name: Format check
      run: |
        black --check amodem/ scripts/
        ruff check amodem/ scripts/

    - name: Type check
      run: |
        mypy amodem/ --ignore-missing-imports

    - name: Test with pytest
      run: |
        pytest -v --cov=amodem
